---
title: "congressionalrecord"
author: "Max Weiss"
date: "9/29/2019"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)

```


```{r blue, include=FALSE}

text <- read_csv("congress_test.csv", col_names = FALSE) %>%
  mutate_if(is.character, replace_na, replace = "") %>%
  mutate(list = paste(X1, X2, X3, X4, X5)) %>%
  select(list)

paste(unlist(text), collapse = "")

```


```{r mauve}
#114
speech114 <- read.table("hein-daily/speeches_114.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr114 <- read.table("hein-daily/descr_114.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_114 <- left_join(descr114, speech114, by = "speech_id")

opioid_114 <- big_114 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_114)
nrow(big_114)

#113
speech113 <- read.table("hein-daily/speeches_113.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr113 <- read.table("hein-daily/descr_113.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_113 <- left_join(descr113, speech113, by = "speech_id")

opioid_113 <- big_113 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_113)
nrow(big_113)

#112
speech112 <- read.table("hein-daily/speeches_112.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr112 <- read.table("hein-daily/descr_112.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_112 <- left_join(descr112, speech112, by = "speech_id")

opioid_112 <- big_112 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_112)
nrow(big_112)

#111
speech111 <- read.table("hein-daily/speeches_111.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr111 <- read.table("hein-daily/descr_111.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_111 <- left_join(descr111, speech111, by = "speech_id")

opioid_111 <- big_111 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_111)
nrow(big_111)

#110
speech110 <- read.table("hein-daily/speeches_110.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr110 <- read.table("hein-daily/descr_110.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_110 <- left_join(descr110, speech110, by = "speech_id")

opioid_110 <- big_110 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_110)
nrow(big_110)

#109
speech109 <- read.table("hein-daily/speeches_109.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr109 <- read.table("hein-daily/descr_109.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_109 <- left_join(descr109, speech109, by = "speech_id")

opioid_109 <- big_109 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_109)
nrow(big_109)

#108
speech108 <- read.table("hein-daily/speeches_108.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr108 <- read.table("hein-daily/descr_108.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_108 <- left_join(descr108, speech108, by = "speech_id")

opioid_108 <- big_108 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_108)
nrow(big_108)

#107
speech107 <- read.table("hein-daily/speeches_107.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr107 <- read.table("hein-daily/descr_107.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_107 <- left_join(descr107, speech107, by = "speech_id")

opioid_107 <- big_107 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_107)
nrow(big_107)

#106
speech106 <- read.table("hein-daily/speeches_106.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr106 <- read.table("hein-daily/descr_106.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_106 <- left_join(descr106, speech106, by = "speech_id")

opioid_106 <- big_106 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_106)
nrow(big_106)

#105
speech105 <- read.table("hein-daily/speeches_105.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr105 <- read.table("hein-daily/descr_105.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_105 <- left_join(descr105, speech105, by = "speech_id")

opioid_105 <- big_105 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_105)
nrow(big_105)

#104
speech104 <- read.table("hein-daily/speeches_104.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr104 <- read.table("hein-daily/descr_104.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_104 <- left_join(descr104, speech104, by = "speech_id")

opioid_104 <- big_104 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_104)
nrow(big_104)

#103
speech103 <- read.table("hein-daily/speeches_103.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr103 <- read.table("hein-daily/descr_103.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_103 <- left_join(descr103, speech103, by = "speech_id")

opioid_103 <- big_103 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_103)
nrow(big_103)

#102
speech102 <- read.table("hein-daily/speeches_102.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

descr102 <- read.table("hein-daily/descr_102.txt", sep = "|", fill = TRUE, header = TRUE) %>%
  mutate(speech_id = as.factor(speech_id))

big_102 <- left_join(descr102, speech102, by = "speech_id")

opioid_102 <- big_102 %>%
  filter(str_detect(speech, regex("Heroin|Opioid|opiate|fentanyl", 
                                  ignore_case = TRUE)))

nrow(opioid_102)
nrow(big_102)

speech111 %>% 
  filter(str_detect(speech, "I yield back our time."))

teste <- read_table("hein-daily/speeches_111.txt", progress = show_progress())
teste2 <- teste %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

glimpse(teste2)

teste %>% filter(nrow()==42301)
teste$`speech_id|speech`[42301]

teste2 %>% filter(speech_id == as.character(1110107946)) 
```
```{r data fix}

big_102a <- big_102 %>%
  mutate(session = 102)
big_103a <- big_103 %>%
  mutate(session = 103)
big_104a <- big_104 %>%
  mutate(session = 104)
big_105a <- big_105 %>%
  mutate(session = 105)
big_106a <- big_106 %>%
  mutate(session = 106)
big_107a <- big_107 %>%
  mutate(session = 107)
big_108a <- big_108 %>%
  mutate(session = 108)
big_109a <- big_109 %>%
  mutate(session = 109)
big_110a <- big_110 %>%
  mutate(session = 110)
big_111a <- big_111 %>%
  mutate(session = 111)
big_112a <- big_112 %>%
  mutate(session = 112)
big_113a <- big_113 %>%
  mutate(session = 113)
big_114a <- big_114 %>%
  mutate(session = 114)

big_all <- rbind(big_102a, big_103a, big_104a, big_105a, big_106a, big_107a, big_108a, big_109a, big_110a, big_111a, big_112a, big_113a, big_114a)

write_rds(big_all, "big_all.rds")

all_samp <- sample_n(big_all,100)
write_csv(all_samp, "all_samp.csv")

```

```{r data build WORKING CHUNK}
descr114 <- read_table("hein-daily/descr_114.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))
descr113 <- read_table("hein-daily/descr_113.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))
descr112 <- read_table("hein-daily/descr_112.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))
descr111 <- read_table("hein-daily/descr_111.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))
descr110 <- read_table("hein-daily/descr_110.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))
descr109 <- read_table("hein-daily/descr_109.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))
descr108 <- read_table("hein-daily/descr_108.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))
descr107 <- read_table("hein-daily/descr_107.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))
descr106 <- read_table("hein-daily/descr_106.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))
descr105 <- read_table("hein-daily/descr_105.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))
descr104 <- read_table("hein-daily/descr_104.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))
descr103 <- read_table("hein-daily/descr_103.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))
descr102 <- read_table("hein-daily/descr_102.txt", col_names = "col") %>%
  separate(`col`, sep = "\\|", into = c("speech_id", "chamber", "date", "number_within_file", "speaker", "first_name", "last_name", "state", "gender", "line_start", "line_end", "file", "char_count", "word_count"))


new114 <- read_table("hein-daily/speeches_114.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join114 <- left_join(new114, descr114, by = "speech_id")


new113 <- read_table("hein-daily/speeches_113.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join113 <- left_join(new113, descr113, by = "speech_id")


new112 <- read_table("hein-daily/speeches_112.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join112 <- left_join(new112, descr112, by = "speech_id")


new111 <- read_table("hein-daily/speeches_111.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join111 <- left_join(new111, descr111, by = "speech_id")

new110 <- read_table("hein-daily/speeches_110.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join110 <- left_join(new110, descr110, by = "speech_id")

new109 <- read_table("hein-daily/speeches_109.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join109 <- left_join(new109, descr109, by = "speech_id")

new108 <- read_table("hein-daily/speeches_108.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join108 <- left_join(new108, descr108, by = "speech_id")

new107 <- read_table("hein-daily/speeches_107.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join107 <- left_join(new107, descr107, by = "speech_id")

new106 <- read_table("hein-daily/speeches_106.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join106 <- left_join(new106, descr106, by = "speech_id")

new105 <- read_table("hein-daily/speeches_105.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join105 <- left_join(new105, descr105, by = "speech_id")

new104 <- read_table("hein-daily/speeches_104.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join104 <- left_join(new104, descr104, by = "speech_id")

new103 <- read_table("hein-daily/speeches_103.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join103 <- left_join(new103, descr103, by = "speech_id")

new102 <- read_table("hein-daily/speeches_102.txt", progress = show_progress()) %>%
  separate(`speech_id|speech`, sep = "\\|", into = c("speech_id", "speech"))

join102 <- left_join(new102, descr102, by = "speech_id")

join102a <- join102 %>%
  mutate(session = 102)
join103a <- join103 %>%
  mutate(session = 103)
join104a <- join104 %>%
  mutate(session = 104)
join105a <- join105 %>%
  mutate(session = 105)
join106a <- join106 %>%
  mutate(session = 106)
join107a <- join107 %>%
  mutate(session = 107)
join108a <- join108 %>%
  mutate(session = 108)
join109a <- join109 %>%
  mutate(session = 109)
join110a <- join110 %>%
  mutate(session = 110)
join111a <- join111 %>%
  mutate(session = 111)
join112a <- join112 %>%
  mutate(session = 112)
join113a <- join113 %>%
  mutate(session = 113)
join114a <- join114 %>%
  mutate(session = 114)

joinall <- rbind(join102a, join103a, join104a, join105a, join106a, join107a, join108a, join109a, join110a, join111a, join112a, join113a, join114a)

write_rds(joinall, "joinall.rds")

join_samp <- sample_n(joinall,100)
write_csv(join_samp, "join_samp.csv")

descr113
glimpse(new113)

descr106 %>% filter(speech_id == as.factor(1060160857))

descr106 %>% filter(speech_id == as.factor(1060000001))
```


```{r freq viz}
fent_102 <- opioid_102 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))
fent_103 <- opioid_103 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))
fent_104 <- opioid_104 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))
fent_105 <- opioid_105 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))
fent_106 <- opioid_106 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))
fent_107 <- opioid_107 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))
fent_108 <- opioid_108 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))
fent_109 <- opioid_109 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))
fent_110 <- opioid_110 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))
fent_111 <- opioid_111 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))
fent_112 <- opioid_112 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))
fent_113 <- opioid_113 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))
fent_114 <- opioid_114 %>%
  filter(str_detect(speech, regex("fentanyl", 
                                  ignore_case = TRUE)))

freq <- tibble(session = c(102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114), 
               opioid = c(nrow(opioid_102), nrow(opioid_103), nrow(opioid_104), nrow(opioid_105), nrow(opioid_106), nrow(opioid_107), nrow(opioid_108), nrow(opioid_109), nrow(opioid_110), nrow(opioid_111), nrow(opioid_112), nrow(opioid_113), nrow(opioid_114)),
               fent = c(nrow(fent_102), nrow(fent_103), nrow(fent_104), nrow(fent_105), nrow(fent_106), nrow(fent_107), nrow(fent_108), nrow(fent_109), nrow(fent_110), nrow(fent_111), nrow(fent_112), nrow(fent_113), nrow(fent_114)),
               total = c(nrow(big_102), nrow(big_103), nrow(big_104), nrow(big_105), nrow(big_106), nrow(big_107), nrow(big_108), nrow(big_109), nrow(big_110), nrow(big_111), nrow(big_112), nrow(big_113), nrow(big_114))) %>%
  mutate(opioid_freq = opioid / total,
         fent_freq = fent / total,
         fent_op = fent / opioid)

freq %>% ggplot(aes(x = session, y = opioid_freq)) +
  geom_col(fill = "darkblue")
  
freq %>% ggplot(aes(x = session, y = fent_freq)) +
  geom_col(fill = "darkblue")

freq %>% ggplot(aes(x = session, y = fent_op)) +
  geom_col(fill = "darkblue")

```





